### ISSUE TITLE
Error in filter_impl(.data, dots) : basic_string::resize

### ISSUE THREAD

**Issue by jibanes** [sewardlee337/finreportr#2] opened 2016-12-29 18:33 UTC
> GetIncome("MSFT", 2016)
Error in filter_impl(.data, dots) : basic_string::resize

> head(GetIncome("AMZN", 2016),5)
                        Metric Units      Amount  startDate    endDate
1    Sales Revenue, Goods, Net   usd 60903000000 2013-01-01 2013-12-31
2    Sales Revenue, Goods, Net   usd 70080000000 2014-01-01 2014-12-31
3    Sales Revenue, Goods, Net   usd 79268000000 2015-01-01 2015-12-31
4 Sales Revenue, Services, Net   usd 13549000000 2013-01-01 2013-12-31
5 Sales Revenue, Services, Net   usd 18908000000 2014-01-01 2014-12-31

**Comment by sewardlee337** [comment] 2017-01-09 22:03
Hi @jibanes, thanks for catching the bug relating to MSFT data. I have added a fix and committed to GitHub. To install patched version, use:

`devtools::install_github("sewardlee337/finreportr")`

Please confirm if the problem is resolved. Thanks!

**Closed as completed** 2017-01-16 22:15 UTC

**Comment by jibanes** [comment] 2017-01-17 15:39
Sorry for the late reply, I will test this thoroughly next week and get back to you.
